# Generated by Django 6.0.5 on 2026-06-05 10:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shipmentphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='itemmanifest',
            name='admin_image',
            field=models.ImageField(upload_to='verified_items/'),
        ),
        migrations.AlterField(
            model_name='itemmanifest',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipmentphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sourcingrequest',
            name='product_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sourcingrequest',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='quote_attachments/'),
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
