# Generated by Django 6.0.5 on 2026-06-11 06:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_order_amount_order_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='invoice_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='supplier_contact',
        ),
        migrations.RemoveField(
            model_name='order',
            name='supplier_invoice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='supplier_notes',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_mode',
            field=models.CharField(choices=[('air', 'Air'), ('sea', 'Sea')], default=346, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='service_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('on_hold', 'On Hold / At Warehouse'), ('shipping', 'Shipping'), ('arrived', 'Arrived'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='on_hold', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
