# Generated by Django 6.0.5 on 2026-06-12 09:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_order_tracking_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierpaymentrequest',
            old_name='amount',
            new_name='invoice_amount',
        ),
        migrations.RemoveField(
            model_name='supplierpaymentrequest',
            name='admin_seen',
        ),
        migrations.RemoveField(
            model_name='supplierpaymentrequest',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='supplierpaymentrequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='supplierpaymentrequest',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='supplierpaymentrequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='supplierpaymentrequest',
            name='address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierpaymentrequest',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierpaymentrequest',
            name='phone',
            field=models.CharField(default='0000000000', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplierpaymentrequest',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='supplierpaymentrequest',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='supplierpaymentrequest',
            name='request_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='supplierpaymentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierpaymentrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
