# Generated by Django 6.0.5 on 2026-06-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_amount_supplierpaymentrequest_invoice_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
