# Generated by Django 6.0.5 on 2026-06-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='order',
            name='links_specs',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sourcing_request',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_number',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='order_products/'),
        ),
    ]
